name: 火山

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  watch:
    types: started
  repository_dispatch:
    types: hs
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm install
      - name: '运行 【火山】'
        run: |
          node hs.js
        env:
          HSURL: ${{ secrets. HSURL }}
          HSHEADER: ${{ secrets. HSHEADER }}
          HSBODY: ${{ secrets. HSBODY }}
          PLAYURL: ${{ secrets. PLAYURL }}
          PLAYHEADER: ${{ secrets. PLAYHEADER }}
          PLAYBODY: ${{ secrets. PLAYBODY }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
